### ISSUE TITLE
Unable to PIN existing CID in IPFS browser node

### ISSUE THREAD

**Issue by logesh2496** [ipfs/helia#139]
Pinning only works If I upload some data using unixfs and then use that CID. I couldn't pin a CID thats already available on ipfs.

So how do I use a CID thats already available on ipfs and pin it in my node?

example: I want to pin this CID: QmRrzxiXGefcF9VbbThGrkhiQeuhPFjRbGgqYZmxYXYkHr on my node

At the moment Im getting the below error:

> errors.js:27 Uncaught (in promise) Error: Not Found
> at Module.notFoundError (errors.js:27:1)
> at MemoryBlockstore.get (memory.js:19:19)
> at #walkDag (pins.js:97:1)
> at eval (pins.js:52:1)
> at eval (index.js:111:1)
> at PQueue._PQueue_tryToStartAnother (index.js:285:1)
> at eval (index.js:135:1)
> at new Promise ()
> at PQueue.add (index.js:99:1)
> at PinsImpl.add (pins.js:51:1)
> at async onPin (ipfs.js:69:17)

**Comment by tabcat** [comment]
I think the answer to this will be first fetching the content and then pinning it (or maybe with a pinning option in the fetch method). But I'm not sure there is a way to fetch a full directory or file using the helia-unixfs package API.

**Comment by achingbrain** [comment]
Can you please share a full repro case please?  Pinning will fetch missing blocks from the network but the error thrown looks like you may be running offline or it could be unrelated.

**Comment by achingbrain** [comment]
Ah, I think there was a small bug with how the internal blockstores were being created - please can you try with `helia@1.2.1`?

**Comment by achingbrain** [comment]
> CustomProgressEvent does not have detail property

[Yes it does](https://achingbrain.github.io/progress-events/classes/CustomProgressEvent.html#detail), but the value is generic according to the event type.

**Comment by marten-seemann** [comment]
@logesh2496 Are you sure these nodes are online? The errors look like handshake timeouts, which you'd expect to see if the nodes has gone offline.

**Comment by achingbrain** [comment]
No, Marten means the remote nodes, the ones being connected to.

**Comment by SgtPooki** [comment]
I can't seem to get files to pin using helia either

**Comment by BigLep** [comment]
@SgtPooki : what repo case were you trying?  (I just want to make sure we're all trying the same thing.)

**Comment by SgtPooki** [comment]
> what repo case were you trying? (I just want to make sure we're all trying the same thing.)

I can't remember at the moment but I will come back to this when I can
