### ISSUE TITLE
Unable to connect with IPFS cluster  in Node js 

### ISSUE THREAD

**Issue by kulwindersingh-ant** [ipfs/helia#205]
I am using following guide to setup IPFS cluster on local
When i try to dial with helia node  p2plib using `/ip4/0.0.0.0/tcp/9094` url
got following errors.

```
/* eslint-disable no-console */

import { noise } from '@chainsafe/libp2p-noise'
import { yamux } from '@chainsafe/libp2p-yamux'
import { unixfs } from '@helia/unixfs'
import { bootstrap } from '@libp2p/bootstrap'
import { tcp } from '@libp2p/tcp'
import { MemoryBlockstore } from 'blockstore-core'
import { MemoryDatastore } from 'datastore-core'
import { createHelia } from 'helia'
import { createLibp2p } from 'libp2p'
import { identifyService } from 'libp2p/identify'
import { multiaddr } from '@multiformats/multiaddr'
import { mplex } from '@libp2p/mplex'
import { webSockets } from '@libp2p/websockets'
import * as Filters from '@libp2p/websockets/filters'
import { json } from '@helia/json'



async function createNode() {
    // the blockstore is where we store the blocks that make up files
    const blockstore = new MemoryBlockstore()

    // application-specific data lives in the datastore
    const datastore = new MemoryDatastore()


    const libp2p = await createLibp2p({
        datastore,

        addresses: {
            listen: [
                '/ip4/127.0.0.1/tcp/0'
            ]
        },


        transports: [
            // webSockets({
            //     filter: Filters.all // this is necessary to dial insecure websockets
            // }),
             tcp(),
            // other transports
        ],
        connectionGater: {
            denyDialMultiaddr: () => false // this is necessary to dial local addresses at all
        },

        connectionEncryption: [
            noise()
        ],
        streamMuxers: [
            yamux()
        ],
        // peerDiscovery: [
        //     bootstrap({
        //         list: [
        //             // '/ip4/127.0.0.1/tcp/5001/p2p/12D3KooWEk4R94wqvqiEFFVM55UjGirgTb5iDXS2ckBUgWe722Lu'
        //             '/ip4/127.0.0.1/tcp/9096/ws/p2p/12D3KooWFsUEkmdZ84ahEJ7efPkekMt7U85ZvQQcdTkhqKnh8JvM'
        //             //'/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
        //             // '/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa',
        //             // '/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
        //             // '/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt'
        //         ]
        //     })
        // ],
        services: {
            identify: identifyService()

        }
    })

    return await createHelia({
        datastore,
        blockstore,
        libp2p
    })
}


async function main() {
    // create two helia nodes
    const node1 = await createHelia()
    const addr = multiaddr("/ip4/0.0.0.0/tcp/9094");
    // console.log("Adderr", addr)

    const conn = await node1.libp2p.dial(addr)

    const j = json(node1)

    const myImmutableAddress = await j.add({ hello: 'world  is gone' })
    console.log("here", myImmutableAddress)
    console.log(await j.get(myImmutableAddress))
    return
```

```

(node:15685) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///Users/user/Works/ejad/blockchain-adaptor/node_modules/libp2p/dist/src/upgrader.js:478
            throw new CodeError(String(err), codes.ERR_ENCRYPTION_FAILED);
                  ^

CodeError: Error: message length too long
    at DefaultUpgrader._encryptOutbound (file:///Users/user/Works/ejad/blockchain-adaptor/node_modules/libp2p/dist/src/upgrader.js:478:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DefaultUpgrader.upgradeOutbound (file:///Users/user/Works/ejad/blockchain-adaptor/node_modules/libp2p/dist/src/upgrader.js:205:21)
    at async WebSockets.dial (file:///Users/user/Works/ejad/blockchain-adaptor/node_modules/@libp2p/websockets/dist/src/index.js:25:22)
    at async DefaultTransportManager.dial (file:///Users/user/Works/ejad/blockchain-adaptor/node_modules/libp2p/dist/src/transport-manager.js:82:20)
    at async queue.add (file:///Users/user/Works/ejad/blockchain-adaptor/node_modules/libp2p/dist/src/connection-manager/dial-queue.js:333:42)
    at async file:///Users/user/Works/ejad/blockchain-adaptor/node_modules/p-queue/dist/index.js:118:36 {
  code: 'ERR_ENCRYPTION_FAILED',
  props: {}
}``
```

**Comment by kulwindersingh-ant** [comment]
https://docs.ipfs.tech/install/server-infrastructure/#create-a-local-cluster

Also this error 
```

            throw new CodeError(String(err), codes.ERR_ENCRYPTION_FAILED);
                  ^

CodeError: CodeError: missing newline
    at DefaultUpgrader._encryptOutbound (file:///Users/user/Works/ejad/blockchain-adaptor/node_modules/libp2p/dist/src/upgrader.js:478:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DefaultUpgrader.upgradeOutbound (file:///Users/user/Works/ejad/blockchain-adaptor/node_modules/libp2p/dist/src/upgrader.js:205:21)
    at async TCP.dial (file:///Users/user/Works/ejad/blockchain-adaptor/node_modules/@libp2p/tcp/dist/src/index.js:50:22)
    at async DefaultTransportManager.dial (file:///Users/user/Works/ejad/blockchain-adaptor/node_modules/libp2p/dist/src/transport-manager.js:82:20)
    at async queue.add (file:///Users/user/Works/ejad/blockchain-adaptor/node_modules/libp2p/dist/src/connection-manager/dial-queue.js:333:42)
    at async file:///Users/user/Works/ejad/blockchain-adaptor/node_modules/p-queue/dist/index.js:118:36 {
  code: 'ERR_ENCRYPTION_FAILED',
  props: {}
}
```

**Comment by SgtPooki** [comment]
@kulwindersingh-ant, we haven't done any testing around ipfs-cluster with Helia that I am aware of. Does https://github.com/ipfs/helia/issues/132 help you at all?

If you have a reproducible example of code we can explore, we might be able to help further.

**Comment by kulwindersingh-ant** [comment]
@SgtPooki i have check #132  but this doesn't work for me

I have setup the cluster from following docs and also shared the example. 
https://docs.ipfs.tech/install/server-infrastructure/#create-a-local-cluster

**Comment by SgtPooki** [comment]
We know we can connect to Kubo & helia nodes successfully (we have interop tests for this). Does your ipfs-cluster output any logs? Maybe you can open an issue on that repo to investigate further?

There is also https://github.com/ipfs-cluster/ipfs-cluster/issues/1931. Maybe check that your cluster is listening on the expected transports & ports?

If you can get a reproduction repository set up we can try to look into this further, but i'm not sure how else to investigate this for now.
