### ISSUE TITLE
Unable to use helia module in react native throwing error while importing

### ISSUE THREAD

**Issue by yogesh2902** [ipfs/helia#250]
Error: InternalError Metro has encountered an error: While trying to resolve module `helia` from file `/Users/--/Desktop/--/src/screens/home/Home.js`, the package `/Users/--/Desktop/--/node_modules/helia/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/--/Desktop/--/node_modules/helia/index`. Indeed, none of these files exist:

**Comment by achingbrain** [comment]
> However, this package itself specifies a main module field that could not be resolved

There is no `"main"` entry in the [package.json](https://github.com/ipfs/helia/blob/main/packages/helia/package.json) - it uses an [exports map](https://nodejs.org/api/packages.html#exports).

React Native has [recently enabled exports map support](https://reactnative.dev/blog/2023/06/21/package-exports-support) though it's opt-in currently - have you tried turning this on?

**Comment by linonetwo** [comment]
Need to add

```
// babel.config.js
plugins: [["@babel/plugin-transform-private-methods", { "loose": true }]],
```

```
//metro.config.js
resolver: {
 unstable_enablePackageExports: true,
```

but still having error

> The package at "node_modules/interface-datastore/node_modules/nanoid/index.js" attempted to import the Node standard library module "crypto".
> It failed because the native React runtime does not include the Node standard library.

**Comment by achingbrain** [comment]
Yes, it seems you'll need to configure your build to polyfill these node core modules.

**Comment by jwoo9928** [comment]
Error still occurs !


error: Error: While trying to resolve module `helia` from file `/Users/jaewoopark/Desktop/multi_wallet/src/components/screens/login/index.tsx`, the package `/Users/jaewoopark/Desktop/multi_wallet/node_modules/helia/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/jaewoopark/Desktop/multi_wallet/node_modules/helia/index`. Indeed, none of these files exist:

  * /Users/jaewoopark/Desktop/multi_wallet/node_modules/helia/index(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg|.ios.cjs|.native.cjs|.cjs)
  * /Users/jaewoopark/Desktop/multi_wallet/node_modules/helia/index/index(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg|.ios.cjs|.native.cjs|.cjs)
    at DependencyGraph.resolveDependency (/Users/jaewoopark/Desktop/multi_wallet/node_modules/metro/src/node-haste/DependencyGraph.js:289:17)
    at Object.resolve (/Users/jaewoopark/Desktop/multi_wallet/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies (/Users/jaewoopark/Desktop/multi_wallet/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule (/Users/jaewoopark/Desktop/multi_wallet/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at async Graph._traverseDependenciesForSingleFile (/Users/jaewoopark/Desktop/multi_wallet/node_modules/metro/src/DeltaBundler/Graph.js:249:5)
    at async Graph.traverseDependencies (/Users/jaewoopark/Desktop/multi_wallet/node_modules/metro/src/DeltaBundler/Graph.js:157:9)
    at async DeltaCalculator._getChangedDependencies (/Users/jaewoopark/Desktop/multi_wallet/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:281:42)
    at async DeltaCalculator.getDelta (/Users/jaewoopark/Desktop/multi_wallet/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:112:16)
    at async DeltaBundler.getDelta (/Users/jaewoopark/Desktop/multi_wallet/node_modules/metro/src/DeltaBundler.js:67:12)
    at async IncrementalBundler.updateGraph (/Users/jaewoopark/Desktop/multi_wallet/node_modules/metro/src/IncrementalBundler.js:224:19)
