### ISSUE TITLE
Valid IPNS records fail to resolve

### ISSUE THREAD

**Issue by 2color** [ipfs/helia#395]
Using the canary tag of the `@helia/http`, trying to resolve the following IPNS record ``, results in the following error:

```
Uncaught (in promise) CodeError: Could not find record for routing key
    at DefaultIPNS.findIpnsRecord_fn (@helia_ipns.js?v=3f44548b:28394:11)
    at async DefaultIPNS.resolve (@helia_ipns.js?v=3f44548b:28319:20)
    at async resolveIpns (index.ts:36:10)
    at async HTMLButtonElement.<anonymous> (index.ts:53:17)
findIpnsRecord_fn @ @helia_ipns.js?v=3f44548b:28394
Show 1 more frame
Show less
```

[Reproduction](https://codesandbox.io/p/github/2color/helia-browser-examples/main?file=%2Fsrc%2Findex.ts%3A14%2C22-14%2C84&workspaceId=96c32827-0145-4a4e-80e4-9201a3af1db9):

**Comment by achingbrain** [comment]
This has been fixed for me after #396
