### ISSUE TITLE
Issues with Yamux / race-signal

### ISSUE THREAD

**Issue by veermetri05** [ipfs/helia#554]
To reproduce just create a Helia instance, 
```
const libp2p = await createLibp2p({
    datastore,
    addresses: {
        listen: [
            '/ip4/127.0.0.1/tcp/0'
        ]
    },
    transports: [
        tcp()
    ],
    connectionEncryption: [
        noise()
    ],
    streamMuxers: [
        yamux()
    ],
    peerDiscovery: [
        bootstrap({
            list: [
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN',
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa',
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb',
                '/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt'
            ]
        })
    ],
    services: {
        identify: identify()
    }
})
const helia = await createHelia(datastore, blockstore, libp2p)
```
and run the program, wait for some time, then you get the issue.
```
return Promise.reject(new AbortError(opts?.errorMessage, opts?.errorCode));
                              ^

AbortError: The operation was aborted
    at raceSignal (file:///C:/Users/VeerMetri/Documents/projects/ipfsDagExperiments/crustLargeFileWorkaround/node_modules/race-signal/dist/src/index.js:22:31)
    at YamuxStream.closeWrite (file:///C:/Users/VeerMetri/Documents/projects/ipfsDagExperiments/crustLargeFileWorkaround/node_modules/@libp2p/utils/dist/src/abstract-stream.js:230:19)
    at YamuxStream.close (file:///C:/Users/VeerMetri/Documents/projects/ipfsDagExperiments/crustLargeFileWorkaround/node_modules/@libp2p/utils/dist/src/abstract-stream.js:189:18)
    at file:///C:/Users/VeerMetri/Documents/projects/ipfsDagExperiments/crustLargeFileWorkaround/node_modules/libp2p/dist/src/connection/index.js:118:63   
    at Array.map (<anonymous>)
    at ConnectionImpl.close (file:///C:/Users/VeerMetri/Documents/projects/ipfsDagExperiments/crustLargeFileWorkaround/node_modules/libp2p/dist/src/connection/index.js:118:44)
    at initiateConnection (file:///C:/Users/VeerMetri/Documents/projects/ipfsDagExperiments/crustLargeFileWorkaround/node_modules/@libp2p/webrtc/dist/src/private-to-private/initiate-connection.js:125:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WebRTCTransport.dial (file:///C:/Users/VeerMetri/Documents/projects/ipfsDagExperiments/crustLargeFileWorkaround/node_modules/@libp2p/webrtc/dist/src/private-to-private/transport.js:91:35)
    at async DefaultTransportManager.dial (file:///C:/Users/VeerMetri/Documents/projects/ipfsDagExperiments/crustLargeFileWorkaround/node_modules/libp2p/dist/src/transport-manager.js:81:20) {
  type: 'aborted',
  code: 'ABORT_ERR'
}

Node.js v20.13.1
```

**Comment by silkroadnomad** [comment]
I have the same error. I had been using:

"helia": "^5.0.0",
"libp2p": "^2.1.10",

"@chainsafe/libp2p-gossipsub": "^14.1.0",
"@chainsafe/libp2p-noise": "^16.0.0",
"@chainsafe/libp2p-yamux": "^7.0.1",
"@helia/interface": "^5.0.0",
"@helia/ipns": "^8.0.0",
"@helia/strings": "^4.0.0",
"@helia/unixfs": "^4.0.0",
"@libp2p/autonat": "^2.0.8",
"@libp2p/bootstrap": "^11.0.8",
"@libp2p/circuit-relay-v2": "^3.0.0",
"@libp2p/crypto": "^5.0.5",
"@libp2p/dcutr": "^2.0.8",
"@libp2p/identify": "^3.0.8",
"@libp2p/interface": "^2.1.3",
"@libp2p/interface-pubsub": "^4.0.1",
"@libp2p/interface-transport": "^4.0.3",
"@libp2p/kad-dht": "^14.0.1",
"@libp2p/logger": "^5.1.1",
"@libp2p/peer-id": "^5.0.5",
"@libp2p/peer-id-factory": "^4.2.4",
"@libp2p/ping": "^2.0.8",
"@libp2p/pubsub-peer-discovery": "^10.0.3",
"@libp2p/tcp": "^10.0.9",
"@libp2p/tls": "^2.0.9",
"@libp2p/upnp-nat": "^2.0.9",
"@libp2p/webrtc": "^5.0.13",
"@libp2p/webrtc-direct": "^6.0.0",
"@libp2p/websockets": "^9.0.9",
"@libp2p/webtransport": "^5.0.13",
"@multiformats/dns": "^1.0.6",
"@multiformats/multiaddr": "^12.3.1",
"@orbitdb/core": "^2.4.2",
"blockstore-core": "^5.0.2",
"blockstore-level": "^2.0.1",
"datastore-core": "^10.0.2",
"datastore-level": "^11.0.1",
"helia": "^5.0.0",
"interface-datastore": "^8.3.1",
"ipns": "^10.0.0",
"libp2p": "^2.1.10",
"multiformats": "^13.3.0",
"uint8arrays": "^5.1.0",
"ws": "^8.18.0"

**Comment by SgtPooki** [comment]
@silkroadnomad please open a small repro case if you can, and open a new issue so we can help you out

**Comment by silkroadnomad** [comment]
@SgtPooki It seemed to have disappeared but today I got it again. The issue is described here more accurately 
https://github.com/libp2p/js-libp2p/issues/2702.

Lets see if I can do a simple reproductive repo.

**Comment by silkroadnomad** [comment]
@veermetri05 your transport shows you have only enabled tcp as transport. Question is: How an issue can pop up in a WebRTC lib then? Are you sure you only enabled WebRTC?

**Comment by jclab-joseph** [comment]
Same issue. Only tcp is enabled.

```json
  "dependencies": {
    "@chainsafe/libp2p-noise": "^16.1.0",
    "@chainsafe/libp2p-yamux": "^7.0.1",
    "@helia/car": "^4.0.4",
    "@helia/unixfs": "^5.0.0",
    "@ipld/car": "^5.4.0",
    "@libp2p/bootstrap": "^11.0.32",
    "@libp2p/identify": "^3.0.27",
    "@libp2p/ping": "^2.0.27",
    "@libp2p/pnet": "^2.0.32",
    "@libp2p/tcp": "^10.1.8",
    "helia": "^5.3.0",
    "libp2p": "^2.8.2",
```

```typescript
const libp2p = await createLibp2p({
      datastore,
      addresses: {
        listen: ['/ip4/127.0.0.1/tcp/0'],
      },
      transports: [tcp()],
      connectionEncrypters: [noise()],
      streamMuxers: [yamux()],
      peerDiscovery: [
        bootstrap({
          list: bootstrapIds,
        }),
      ],
      connectionProtector: preSharedKey({
        psk: textEncoder.encode(swarmKey),
      }) as any,
      services: {
        identify: identify(),
        ping: ping(),
      },
    });
```
